int citrus
Signed-off-by: aseelps <aseelpsathar@gmail.com>

diff --git a/build b/build
--- a/build
+++ b/build
@@ -3,34 +3,34 @@ cd /tmp/rom # Depends on where source got synced
 
 ## Normal build steps
 . build/envsetup.sh
-lunch dot_vince-userdebug
+lunch dot_juice-userdebug
 export CCACHE_DIR=/tmp/ccache
 export CCACHE_EXEC=$(which ccache)
 export USE_CCACHE=1
-ccache -M 20G # It took only 6.4GB for vince
+ccache -M 20G # It took only 6.4GB for juice
 ccache -o compression=true # Will save times and data to download and upload ccache, also negligible performance issue
 ccache -z # Clear old stats, so monitor script will provide real ccache statistics
 
 # Next 8 lines should be run first to collect ccache and then upload, after doning it 1 or 2 times, our ccache will help to build without these 8 lines.
-#make api-stubs-docs || echo no problem, we need ccache
-#make system-api-stubs-docs || echo no problem we need ccache
-#make test-api-stubs-docs || echo no problem, we need ccache
-#make bacon -j8 & # dont remove that '&'
-#sleep 75m
-#kill %1
-#ccache -s
+make api-stubs-docs || echo no problem, we need ccache
+make system-api-stubs-docs || echo no problem we need ccache
+make test-api-stubs-docs || echo no problem, we need ccache
+make bacon -j8 & # dont remove that '&'
+sleep 75m
+kill %1
+ccache -s
 #and dont use below codes for first 1 or 2 times, to get ccache uploaded,
 
 
 # upload function for uploading rom zip file! I don't want unwanted builds in my google drive haha!
-#up(){
-#	curl --upload-file $1 https://transfer.sh/$(basename $1); echo
-#	# 14 days, 10 GB limit
-#}
+up(){
+	curl --upload-file $1 https://transfer.sh/$(basename $1); echo
+	# 14 days, 10 GB limit
+}
 
 # It's recommended to use google drive(rclone) as upload solution for coping with the time limit. Un-comment next 3 lines to upload with rclone in drive. Also change apon and junk according to your config name, uploading folder of drive
 up(){
-	time rclone copy $1 cli:junk -P # apon is my rclone config name, 
+	time rclone copy $1 m3:junk -P # apon is my rclone config name, 
 }
 
 tg(){
@@ -49,14 +49,14 @@ echo "$rclone_config" > ~/.config/rclone/rclone.conf
 # Upload rom zip file if succeed to build! Send notification to tg! And send shell to tg if build fails!
 
 #Let's compile by parts! Coz of ram issue!
-make api-stubs-docs || echo no problem
-make system-api-stubs-docs || echo no problem
-make test-api-stubs-docs || echo no problem
+#make api-stubs-docs || echo no problem
+#make system-api-stubs-docs || echo no problem
+#make test-api-stubs-docs || echo no problem
 
-make bacon -j8 \
-	&& send_zip=$(up out/target/product/vince/*zip) && tg $id "Build Succeed!
-$send_zip" \
-	|| tmate -S /tmp/tmate.sock new-session -d && tmate -S /tmp/tmate.sock wait tmate-ready && send_shell=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}') && tg $id "Build Failed" && tg $id "$send_shell" && ccache -s && sleep 2h
-ccache -s # Let's print ccache statistics finally
+#make bacon -j8 \
+#	&& send_zip=$(up out/target/product/juice/*zip) && tg $id "Build Succeed!
+#$send_zip" \
+#	|| tmate -S /tmp/tmate.sock new-session -d && tmate -S /tmp/tmate.sock wait tmate-ready && send_shell=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}') && tg $id "Build Failed" && tg $id "$send_shell" && ccache -s && sleep 2h
+#ccache -s # Let's print ccache statistics finally
 
-tg $id "Build Uploaded successfully" 
+#tg $id "Build Uploaded successfully" 
